# -*- coding: utf-8 -*-
"""hw-09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xnSpc-5B2HP9DYz4y9Px_jtGamHI1gzq

Задача 40: Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)
"""

import pandas as pd
df = pd.read_csv('california_housing_train.csv')
small_population = df.loc[(0 < df.population) & (df.population < 500)]
small_population.median_house_value.mean()

"""Задача 42: Узнать какая максимальная households в зоне минимального значения population"""

min_population_zone = df.loc[df.population < df.population.quantile(.25)]
min_population_zone.households.max()